[workspace]
resolver = "2"

members =  [
	"virtio-blk",
	"virtio-queue",
	"virtio-bindings",
]

[workspace.package]
version = "0.1.0"
authors = ["Debin <luodeb@outlook.com>"]
license = "GPL-3.0-or-later OR Apache-2.0 OR MulanPSL-2.0"
homepage = ""
repository = ""

[workspace.dependencies]
